apiVersion: apps/v1
kind: Deployment
metadata:
  name: javawebappdeployment
  labels:
    app: javawebapp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: javawebapp
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 30
  template:
    metadata:
      labels:
        app: javawebapp
    spec:
      containers:
      - name: javawebappcontainer
        image: 447083649628.dkr.ecr.ap-south-1.amazonaws.com/java-web-app:${buildNumber}
        ports:
        - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: service1
spec:
  type: NodePort 
  selector:
    app: javawebapp
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
